apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sample-assembly
  labels:
    app: {{ .Release.Name }}-sample-assembly
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-sample-assembly
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 80